TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"
INSTAGRAM_API_URL = "https://api.instagram.com/..."
TIKTOK_API_URL = "https://api.tiktok.com/..."
CLICK_TOKEN = "YOUR_CLICK_API_KEY"
PAYME_TOKEN = "YOUR_PAYME_API_KEY"
ADMIN_ID = 123456789